### PR TITLE
keep in sync with jetstream user creation

### PR DESCRIPTION
**Pull request by rokde**

### CODE REVIEW

**Comment by rokde** [comment]
Hard to test, because the used trait is in jetstream application existing. Do you have any idea? Otherwise remove my PR. Your code does work too.

**Comment by joelbutcher** [comment]
You can test this by including fortify in composer. However, I'm not 100% sure what you're trying to achieve here, is it just to reduce the maintenance burden of updating the class in the instance Jetstream changes their password validation rules?

**Comment by rokde** [comment]
Yes, I only wanted to reduce maintenance stuff. And to remove the gap between jetstream und socialstream.

**Comment by joelbutcher** [comment]
Okay, I'll investigate this myself and submit a fix today. Thanks for all your work today - really helpful stuff merged in!

**Pull request closed without merging**
