### PR TITLE
[5.x] fix: duplicate route names

### PR DESCRIPTION
**Pull request by joelbutcher**
Uses `Route::match(…)` to resolve the OAuth callback for both GET and POST HTTP verbs in order to cache the route for both methods with the same name.

Addresses issues identified in #288

### CODE REVIEW

**Comment by joelbutcher** [comment]
Requires tests to ensure caching isn't broken

**Comment by Supernova3339** [comment]
any progress on this?

**Comment by SRWieZ** [comment]
I just ran into this error. Glad the solution already exists. Will wait for the next release. Thanks for the package!

**Comment by joelbutcher** [comment]
@Supernova3339 feel free to use the dev branch that I'm currently working on. No date for release yet.

**Comment by joelbutcher** [comment]
@Supernova3339 nope. I've had a pretty bad flu/cold for the last week or so and still recovering. Will carve out some time for it this week, but I have no set date for release.

When it's out, you will be the first to know 👍

**Comment by Supernova3339** [comment]
Awesome! Thanks, Joel!

**Pull request merged**
